version: '3.9'

services:
  inventory-service:
    build:
      context: .
      dockerfile: apps/inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - '9004:9004'
    restart: unless-stopped
