version: '3.9'

services:
  payment-service:
    build:
      context: .
      dockerfile: apps/payment-service/Dockerfile
    container_name: payment-service
    ports:
      - '9007:9007'
    restart: unless-stopped
