version: '3.9'

services:
  cart-service:
    build:
      context: .
      dockerfile: apps/cart-service/Dockerfile
    container_name: cart-service
    ports:
      - '9005:9005'
    restart: unless-stopped
