version: '3.9'

services:
  mail-service:
    build:
      context: .
      dockerfile: apps/mail-service/Dockerfile
    container_name: mail-service
    ports:
      - '9011:9011'
    restart: unless-stopped
