version: '3.9'

services:
  order-service:
    build:
      context: .
      dockerfile: apps/order-service/Dockerfile
    container_name: order-service
    ports:
      - '9006:9006'
    restart: unless-stopped
