version: '3.9'

services:
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: user-service
    ports:
      - '9001:9001'
    restart: unless-stopped
