version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - '9010:9010'
    restart: unless-stopped
