version: '3.9'

services:
  customer-service:
    build:
      context: .
      dockerfile: apps/customer-service/Dockerfile
    container_name: customer-service
    ports:
      - '9002:9002'
    restart: unless-stopped
